apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: shopping-cart
  namespaceSelector:
    matchNames:
    - dev
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
